apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: aws-101-vpc-ec2-madhueaasutility
  project: madhueaasutility
spec:
  envs:
  - key: AWS_ACCESS_KEY_ID
    sensitive: true
    value: sealed://AWS_ACCESS_KEY_ID
  - key: AWS_SECRET_ACCESS_KEY
    sensitive: true
    value: sealed://AWS_SECRET_ACCESS_KEY
  secret:
    name: file://artifacts/aws-101-vpc-ec2-madhueaasutility/sealed-secret.yaml
