apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: gcp-101-vpc-instance-madhueaasutility
  project: madhueaasutility
spec:
  envs:
  - key: GOOGLE_CREDENTIALS
    value: get-started.json
  files:
  - data: c2VhbGVkOi8vZmlsZXMuMA==
    name: get-started.json
    sensitive: true
  secret:
    name: file://artifacts/gcp-101-vpc-instance-madhueaasutility/sealed-secret.yaml
