apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-bedrock-openai-qdrant.fullname" . }}-frontend
  labels:
    {{- include "rag-bedrock-openai-qdrant-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rag-bedrock-openai-qdrant-frontend.selectorLabels" . | nindent 4 }}
