apiVersion: v1
kind: Service
metadata:
  name: gen-ai
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gen-ai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-ai
spec:
  selector:
    matchLabels:
      app: gen-ai
  replicas: 1
  template:
    metadata:
      labels:
        app: gen-ai
    spec:
      containers:
      - name: gen-ai
        image: registry.dev.rafay-edge.net/rafay/genai-sample-app:1.2
        ports:
        - containerPort: 80
      serviceAccountName: gen-ai
---
