apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rkd-dev-test
  namespace: default
spec:
  encryptedData:
    variables.3: AQBa0+5nrBJPkOk+MQgOzDVuh7djbE968OzGfXo2n+LtuX3lyKRyiBrF8FcEEnBFOtbrfV1LDx1/hq17jkbd1yuI8C2PBFb1vP9ihwULlOBgsJE3p57GvpODSvujF2iEWX/U9/nMDLKzGa/aGhPXqV/N116IwxFSRC5RsLDqhlApaAi5y01ss4ZFDMrMMSDaupOFWMznvKk/4aIUTgvecnT9dmn+U2MVV5mAL1X/jg2r+c3BGetHBYR25MrlevssGGKMnpFDhjPbfER2JJyjIprqQfNH3wwCy3M5gQYw+p6GBBMLLs/WdIDrCyfmYw1wDryPby1+gL6XJprhdmU0MsnmGtz4O5gRA0vpvKlnufG/gIkSVmCvXPrWiQ6m1FPuOUgQex86
    variables.4: AQC6GdZtHfKurWWvtzT248Oa5o3vxVyCRelWFrxHk1L6U06BSqQP+sKYIzi8kmWmwkOsSWmWXQ0qd0cwIGRhi4vTeu4iDl6uCr7Lh/n49D7gQQp6ioijo0zkrgc3a2S9z7uLAnsELMC7pdGqU/Z94JIJq0IgGX40iLsQQ+QVL69Zuy2OQ+NSv8CKUBT44ibphMh49w2+/jKITr9d2JGsCvt7PPbgH+XakYJj+RyjVkWazl8LtQmIA6Yao66QVMfaHrnO0FU7Vqrv/ofAC1e1VtEfy7I5q5MdKAkJs953omDb1BMwZN+8+jXiaTH5zC/A9d87tg2LtLJejZmrUDIVhs5vLE6bTZOpzTaFSquUbIyThOuaxn87AldAiACI/g6WGvPP/3qOGBTEmEiWlVeH9b/b+k3StMkt2Q4=
  template:
    metadata:
      creationTimestamp: null
      name: rkd-dev-test
      namespace: default

