apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: madhu-vpc
  project: madhueaasutility
spec:
  agents:
  - name: madhueaasagent210
  template:
    name: vpc-and-security-group
    version: v1
    versionState: active
  variables:
  - name: azs
    options:
      override:
        type: allowed
      required: true
    value: '["us-west-2a","us-west-2b","us-west-2c"]'
    valueType: hcl
  - name: create_database_subnet_group
    options:
      override:
        type: allowed
      required: true
    value: "true"
    valueType: hcl
  - name: database_subnets
    options:
      override:
        type: allowed
      required: true
    value: '["10.0.7.0/24", "10.0.8.0/24", "10.0.9.0/24"]'
    valueType: hcl
  - name: private_subnets
    options:
      override:
        type: allowed
      required: true
    value: '["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]'
    valueType: hcl
  - name: public_subnets
    options:
      override:
        type: allowed
      required: true
    value: '["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]'
    valueType: hcl
  - name: region
    options:
      override:
        type: allowed
      required: true
    value: us-west-2
    valueType: text
