apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rkd-dev-test-nov14-1
  project: dev-project
spec:
  blueprintConfig:
    name: default
  cloudCredentials: aws-cloud-creds-1
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    metadata:
      name: rkd-dev-test-nov14-1
      region: us-west-2
      tags:
        email: test@rafay.co
        env: qa
      version: "1.26"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.large
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 1
      name: ng-1
      privateNetworking: true
      subnets:
      - subnet-0d6995c0963ddf08d
      - subnet-036ff9a08547d140e
      - subnet-08ab44cf89361708c
      tags:
        email: test@rafay.co
        env: qa
      version: "1.26"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      subnets:
        private:
          subnet-08ab44cf89361708c:
            id: subnet-08ab44cf89361708c
          subnet-036ff9a08547d140e:
            id: subnet-036ff9a08547d140e
          subnet-0d6995c0963ddf08d:
            id: subnet-0d6995c0963ddf08d
        public:
          subnet-05bb5dca7b9e1c78d:
            id: subnet-05bb5dca7b9e1c78d
          subnet-08970fe282ebb0845:
            id: subnet-08970fe282ebb0845
          subnet-0905489413c7e93f1:
            id: subnet-0905489413c7e93f1
  type: aws-eks
