apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rkd-dev-test-nov14
  project: dev-project
spec:
  blueprintConfig:
    name: default
  cloudCredentials: aws-cloud-creds-1
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    metadata:
      name: rkd-dev-test-nov14
      region: us-west-2
      tags:
        email: test@rafay.co
        env: qa
      version: "1.26"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.large
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 1
      name: ng-1
      privateNetworking: true
      subnets:
      - subnet-026522278dfa41627
      - subnet-0d6626b0ffd8edff5
      - subnet-075bf40efbc1b98f9
      tags:
        email: test@rafay.co
        env: qa
      version: "1.26"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      subnets:
        private:
          subnet-075bf40efbc1b98f9:
            id: subnet-075bf40efbc1b98f9
          subnet-026522278dfa41627:
            id: subnet-026522278dfa41627
          subnet-0d6626b0ffd8edff5:
            id: subnet-0d6626b0ffd8edff5
        public:
          subnet-05c28b254deb8bc6b:
            id: subnet-05c28b254deb8bc6b
          subnet-09a376462a5169ec2:
            id: subnet-09a376462a5169ec2
          subnet-0c505be173cfa059a:
            id: subnet-0c505be173cfa059a
  type: aws-eks
