##Rafay Project name
projectName: UPDATE_EXISTING_PROJECT_NAME
## Initial Version for Environment Manager resources.
version: v1
## https://docs.rafay.dev/env_manager/overview/
## Environment Manager congifContext Name
## https://docs.rafay.dev/env_manager/templates/contexts/
OCIConfigContext: oci-101-caas-oke
RafayConfigContext: rafay-101-caas-oke
## https://docs.rafay.dev/env_manager/overview/
## Environment Manager Driver Name
OCIDriver: oci-driver
##Environment Manager resourceTemplate Name
## https://docs.rafay.dev/env_manager/templates/resource_templates/
ProjectResourceTemplate: rafay-project
GroupResourceTemplate: rafay-group-association
OCIOKEResourceTemplate: oci-vcn-oke
ImportResourceTemplate: oke-import
PauseResourceTemplate: pause
## Environment Manager environmentTemplate Name
## https://docs.rafay.dev/env_manager/templates/environment_templates/
EnvironmentTemplate: caas-oke
## Terraform code path 
tfRepoPathProject: terraform/oci/101-caas-oke/terraform/project
tfRepoPathGroup: terraform/oci/101-caas-oke/terraform/group
tfRepoPathOCIOKE: terraform/oci/101-caas-oke/terraform/vcn-oke
tfRepoPathImport: terraform/oci/101-caas-oke/terraform/rafay-import
tfRepoPathPause: terraform/oci/101-caas-oke/terraform/pause
## Other Variables
ociRegion: UPDATE_OCI_REGION

