apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eaas-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBY2Y8XxWvw1mkrMr1mOGmy3IPu+L6QuUsCUA8ksX/e2MN/rDZD7ghf7dig5Ifg8RGOos/qOuXt6wlv5Pfq+2bM+DNuclcUvmgCz9FRJAVgcubnRP8o54frOnZY+VWUddfePPv1mXUIgasZcBZB+Tu1RzXezALOQFkSmWLPCdtxwBHjnBm6Y1vKoI1wzYieKL3yFc5V7VxBLrhpZouAcNYdzlQFGMKCBGGJLX7gtlyINgH3Hci7B3LUPO7ASooRPPXTMGUJor9kR8FN4U7LQU5aDUIPk8bea0nxRTxZu5UtS72f66hfi5ljkSHhidHrZ3axfv41tP2eQzrYfN+KMfM+0R9u4rGBsgIuzDdfhQasegzrAXa1pjExgAHVw3b2YoxshA36wCXdZqWO0oZR781WVAmoYa8mHGw=
  template:
    metadata:
      creationTimestamp: null
      name: eaas-repo
      namespace: default

