projectName: rkd-apr29
agentName: eaas-agent
repoName: eaas-repo
branch: main

## Initial Version for Environment Manager resources.
version: v1
ConfigContext: aws-101-vpc-ec2

VPCResourceTemplate: vpc
VPCEndpointsResourceTemplate: vpc-endpoints

EC2ResourceTemplate: ec2

SecurityGroupResourceTemplate: security-group
SecurityGroupSSHResourceTemplate: security-group-ssh

RDSResourceTemplate: rds

IamUserResourceTemplate: iam-user
IamRoleForServiceAccountResourceTemplate: iam-service-accounts-eks
IamReadOnlyPolicyResourceTemplate: iam-read-only-policy
IamPolicyResourceTemplate: iam-policy
IamGroupWithPolicyResourceTemplate: iam-group-with-policies
IamGroupWithAssumableRolesPolicyResourceTemplate: iam-group-with-assumable-roles-policy
IamGithubOidcResourceTemplate: iam-github-oidc-role
IamGithubOidcProviderTemplate: iam-github-oidc-provider
IamEksRoleTemplate: iam-eks-role
IamAssumableRolesTemplate: iam-assumable-roles
IamAssumableRolesWithSamlTemplate: iam-assumable-roles-with-saml
IamAssumableRoleTemplate: iam-assumable-role
IamAssumableRoleWithSamlTemplate: iam-assumable-role-with-saml
IamAssumableRoleWithOidcTemplate: iam-iam-assumable-role-with-oidc
IamAccountTemplate: iam-account

tfVPCRepoPath: /terraform/aws-resources-public/terraform-aws-vpc
tfEC2RepoPath: /terraform/aws-resources-public/terraform-aws-ec2-instance
tfSecurityRepoPath: /terraform/aws-resources-public/terraform-aws-security-group
tfRdsRepoPath: /terraform/aws-resources-public/terraform-aws-rds
tfIamRepoPath: /terraform/aws-resources-public/terraform-aws-iam/modules

EC2EnvironmentTemplate: aws-vpc-ec2-env

## Cloudwatch
CloudwatchCisAlarmsResourceTemplate: aws-cloudwatch-cis-alarms
tfCloudwatchCisAlarmRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchCompositeAlarmsResourceTemplate: aws-cloudwatch-composite-alarms
tfCloudwatchCompositeAlarmRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchLogGroupResourceTemplate: aws-cloudwatch-log-group
tfCloudwatchLogGroupRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchLogMetricFilterResourceTemplate: aws-cloudwatch-log-metric-filter
tfCloudwatchLogMetricFilterGroupRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchLogStreamResourceTemplate: aws-cloudwatch-log-stream
tfCloudwatchLogStreamGroupRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchMetricAlarmResourceTemplate: aws-cloudwatch-metic-alarm
tfCloudwatchMetricAlarmRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchMetricAlarmsByMultipleResourceTemplate: aws-cloudwatch-metic-alarms-by-multiple
tfCloudwatchMetricAlarmsByMultipleRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchMetricStreamResourceTemplate: aws-cloudwatch-metic-stream
tfCloudwatchMetricStreamRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch

CloudwatchQueryDefinitionResourceTemplate: aws-cloudwatch-query-definition
tfCloudwatchQueryDefinitionRepoPath: /terraform/aws-resources-public/terraform-aws-cloudwatch


## EFS
EfsResourceTemplate: aws-efs
tfEfsRepoPath: /terraform/aws-resources-public/terraform-aws-efs

## S3 bucket
S3BucketResourceTemplate: aws-s3-bucket
tfS3BucketRepoPath: /terraform/aws-resources-public/terraform-aws-s3

S3BucketNotificationResourceTemplate: aws-s3-bucket-notification
tfS3BucketNotificationRepoPath: /terraform/aws-resources-public/terraform-aws-s3

S3BucketObjectResourceTemplate: aws-s3-bucket-object
tfS3BucketObjectRepoPath: /terraform/aws-resources-public/terraform-aws-s3

## Route53
Route53RecordsResourceTemplate: aws-route53-records
tfRoute53RecordsRepoPath: /terraform/aws-resources-public/terraform-aws-route53-records

Route53DelegationSetsResourceTemplate: aws-route53-delegation-sets
tfRoute53DelegationSetsRepoPath: /terraform/aws-resources-public/terraform-aws-route53

Route53DelegationZonesResourceTemplate: aws-route53-delegation-zones
tfRoute53DelegationZonesRepoPath: /terraform/aws-resources-public/terraform-aws-route53

Route53DelegationResolverRuleAssociationsResourceTemplate: aws-route53-delegation-resolver-rule-associations
tfRoute53DelegationResolverRuleAssociationsRepoPath: /terraform/aws-resources-public/terraform-aws-route53



region: us-west-2
