apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  name: app-environment-template2
  project: dev-project
spec:
  agents:
  - name: dev-agent
  contexts:
  - name: rafay-config-context
  resources:
  - kind: resourcetemplate
    name: vpc-resource-template
    resourceOptions:
      version: v1
    type: dynamic
  - dependsOn:
    - name: vpc-resource-template
    kind: resourcetemplate
    name: eks-resource-template
    resourceOptions:
      version: v1
    type: dynamic
  - dependsOn:
    - name: eks-resource-template
    kind: resourcetemplate
    name: namespace-resource-template
    resourceOptions:
      version: v1
    type: dynamic
  schedules:
  - cadence:
      cronExpression: 59 23 * * *
      cronTimezone: Europe/London
    context:
      name: appresizer-config-context
    name: 'daily-schedule '
    optOutOptions:
      allowOptOut: false
    type: workflows
    workflows:
      tasks:
      - agents:
        - name: rctl-003
        driver:
          name: appresizer
        name: AppResizeRun
        onFailure: unspecified
        options: {}
        type: driver
  variables:
  - name: cluster_name
    options:
      override:
        type: allowed
      required: true
    valueType: text
  version: v1
  versionState: active
