apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rafay-config-context
  namespace: default
spec:
  encryptedData:
    RCTL_API_KEY: AQCoKi1M0mDzrPwc8nEIY4j/+1znN6qQbCP1sp5LC5lZ4qFAPBLsa7hvnXsaJuSVhqrPY733ViKGFc7a0mfKhDa1A3AJyazUJzH8Xbm+vzqx7Bb0BRFdZYS9saVc1lBKusWdqnx/o71ChOIWR04c6VEbMePGNLGtE1bwegduHXEnxb75B3R5K2hMKmYKt6nsLMvXflkbQvpAO68yqsl91s9vl69dpw14q00eO4Z+hDgsfOIJ0zaBAuXTpVyyNhlGNFAnMK4vpQJs9nsP+6fk5mrF5BvrrFSZ5GpWMbqBgf/Mg0vHQHzglKvImbwug9xrPsVIX1pcc4oBl5fgkZlsco8yl3doEdiTllxj9CXuViPDlsUpAMCeBJH1/G/TsR59iPlgI6QdfUSb582WnR+hTm3EFsRIjrWPbIK+TTl5yTdLvYsZGLHCZzX4E6ZW/AQv7Ud8wwgwCHgY2oquDwC3VUSClSXno4KbckciIe+g1eRDNc0xBIwx2lLxQEqP/WI=
    RCTL_API_SECRET: AQCMZzkwvNBM21tD1GZI0xlPLfvgUAAnoMlOPxvfy7H3pC1d+Ibcuf+Wc1sRdp1DCuheDKV+UqL0SRTjEmK/OmSs17sngUKJ1PGGzB7AvXKp5mnPWmmO8nkz4qydXsOXxI7YKTNtyazUyWkXjOf5uMW5hByj4amp5UC1wuDbf2cu4JflmZgVthIKZ5cxHO9K74alKhyeWP83q7dH+JP+Tr7m7ceFHcHK768WR+XdRUtLtDn/mJg3hv4hGtiKNWf9xI2DjuNyWNo2ZIpfdk8kwScQ3CnS6jn9OIiOv/CBGZR4omiofk1cSzGzNLSNseV2mHxlJ0WrMrTXm2oyDKcBHY/L0ahdhTIuI6A8ssIU4Ip1yOpoUEmzLfIqUda7GhJyAMNhCKfhbna03F20GVXyWIF0jsreH6w0StwDMZCBqqky1o5CLQdlLwNsq1oGKLIGNV4=
    variables.0: AQAxE2jXGkR7bKNz2XTQemST2VJkik9y6BozWMP7isLyUG8bG3Z2ViDfoELUhCxtfeeEkh+jcdEJ8qXJa1NDvrFu9N6FMlJmjMBRFnPbwOwCcypp++l9yyvDxcu62vZW7wL7t0ar2QAWouyPRib8Xqk3N3lpjERFkc+wiWsdHWybNYN2mc9x/SmsRCfIfC0gCdDECK0mM6N15E59feVduqBlMBgsqVMTpG7brytEXlVJizNAfeKFKGOmP5UbgHdscIWanoVRen3zSu6F7dBkft3RXz6WbusN747KHxFHeZbjV9zBg2I8uMNsg3/qykZiqAUFAbTtmLepzeXNyVu5OoBgMXxoR/zWXttHdN65+Cbbk6N3bVmjPiZ6t6VKYo2jk+d4Q/8W
    variables.1: AQBD6B2L+05O9kr8TSVajWEOvGsav3iPgzWaxdrMHHYaKNXmZKju29M8DHCilevyx4wb+pZyZH/3kpOUQicz9FETZGtGWxlWLEJyW/FzcKTvoQea5YPycTTx+8zEusppkOlIrvYQjhV/46FdO6MtAWHJUJ06GV09Ij3O+Yd1x2upat3Vbpu4LPkVEdHx0UUZdIMfvPa8rqiqV9P02TZw1/gDa9UP1intnrXbzsGzP5qtZvClKK0ZIFMVBWfV5u8V3hWDt+OClPpTxbq0ONVLq4NreS/mQg6QlPwLAad0Y6XFqXE8Fc4F2FsMOEy6Xyvg4cd5FwNZjPuISD302mpv4LkEOfvQHI7aJQX/JZk1BMBJ0Hp7bvBW31qWQp99/cHXieGMxCO2vZ/48ljcV9XjQFRZMTbv82e1dD0=
  template:
    metadata:
      creationTimestamp: null
      name: rafay-config-context
      namespace: default

