module "terraform-aws-iam" {
  source  = "terraform-aws-iam//modules/iam-assumable-roles"
  version = "5.39.0"

  trusted_role_actions = var.trusted_role_actions
  trusted_role_arns = var.trusted_role_arns
  trusted_role_services = var.trusted_role_services
  mfa_age = var.mfa_age
  allow_self_assume_role = var.allow_self_assume_role
  create_admin_role = var.create_admin_role
  admin_role_name = var.admin_role_name
  admin_role_path = var.admin_role_path
  admin_role_requires_mfa = var.admin_role_requires_mfa
  admin_role_policy_arns = var.admin_role_policy_arns
  admin_role_permissions_boundary_arn = var.admin_role_permissions_boundary_arn
  admin_role_tags = var.admin_role_tags
  create_poweruser_role = var.create_poweruser_role
  poweruser_role_name = var.poweruser_role_name
  poweruser_role_path = var.poweruser_role_path
  poweruser_role_requires_mfa = var.poweruser_role_requires_mfa
  poweruser_role_policy_arns = var.poweruser_role_policy_arns
  poweruser_role_permissions_boundary_arn = var.poweruser_role_permissions_boundary_arn
  poweruser_role_tags = var.poweruser_role_tags
  create_readonly_role = var.create_readonly_role
  readonly_role_name = var.readonly_role_name
  readonly_role_path = var.readonly_role_path
  readonly_role_requires_mfa = var.readonly_role_requires_mfa
  readonly_role_policy_arns = var.readonly_role_policy_arns
  readonly_role_permissions_boundary_arn = var.readonly_role_permissions_boundary_arn
  readonly_role_tags = var.readonly_role_tags
  max_session_duration = var.max_session_duration
  force_detach_policies = var.force_detach_policies
}
