##Rafay Project name
projectName: UPDATE_EXISTING_PROJECT_NAME
##Rafay gitops agent name
agentName: eaas-agent
##Rafay respository name
repoName: eaas-repo
##Username to access repository
usernName: UPDATE_REPO_USERNAME
##Token to access repository
token: UPDATE_REPO_TOKEN
##Repository url
endPoint: UPDATE_REPO_ENDPOINT
##Repository revision name
branch: UPDATE_REPO_BRANCH
## Repository path for Rafay to write back configuration.
path: rafay-resources
## Initial Version for Environment Manager resources.
version: v1
## https://docs.rafay.dev/env_manager/overview/
## Environment Manager congifContext Name
## https://docs.rafay.dev/env_manager/templates/contexts/
AWSConfigContext: aws-101-waas-eks
RafayConfigContext: rafay-101-waas-eks
##Environment Manager resourceTemplate Name
## https://docs.rafay.dev/env_manager/templates/resource_templates/
VPCResourceTemplate: aws-vpc-rs-tmpl
EKSResourceTemplate: aws-eks-rs-tmpl
WorkspaceResourceTemplate: aws-workspace-eks-rs-tmpl
## Environment Manager environmentTemplate Name
## https://docs.rafay.dev/env_manager/templates/environment_templates/
InfraEnvironmentTemplate: eks-waas-infra-env-tmpl
WorkspaceEnvironmentTemplate: eks-waas-env-tmpl
#Environment: eks-kubelow-env
## Terraform code path 
tfRepoPathVPC: terraform/aws/101-waas-eks/terraform/vpc
tfRepoPathEKS: terraform/aws/101-waas-eks/terraform/eks
tfRepoPathWorkspace: terraform/aws/101-waas-eks/terraform/workspace
awsRegion: us-west-2
EKSClusterName: waas-eks-cluster
