apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  name: aws-ecs-vpc-env-tmpl-madhueaasutility
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  resources:
  - kind: resourcetemplate
    name: 101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility
    resourceOptions:
      version: v1
    type: dynamic
  - dependsOn:
    - name: 101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility
    kind: resourcetemplate
    name: 101-vpc-ecs-aws-ecs-rs-tmpl-madhueaasutility
    resourceOptions:
      version: v1
    type: dynamic
  version: v1
  versionState: active
