apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  name: gcp-vnet-vm-env-tmpl-madhueaasutility
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  resources:
  - kind: resourcetemplate
    name: gcp-vnet-vm-rs-tmpl-madhueaasutility
    resourceOptions:
      version: v1
    type: dynamic
  version: v1
  versionState: active
