apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  description: Create a Postgres RDS database in an existing AWS VPC and Security
    Group
  displayName: AWS RDS Postgres Database
  name: rds
  project: madhueaasutility
spec:
  iconURL: https://cloud-icons.onemodel.app/aws/Architecture-Service-Icons_01312023/Arch_Database/64/Arch_Amazon-RDS_64.svg
  readme: "## Introduction\n\nUsers can use this template to create an RDS PostgreSQL
    Database in AWS within an existing VPC \n\n---\n\n## What does this do behind
    the scenes? \n\nThis template will perform the following in a sequence: \n\n1.
    Create a new RDS PostreSQL database in AWS within the specified existing VPC\n
    \n\n---\n\n## Defaults and Overrides \nUnless specified, the new database will
    be created with the default settings. Users have the option to override the defaults
    with alternative options. See the input variables section below for complete details. "
  resources:
  - kind: resourcetemplate
    name: rafay-aws-rds
    resourceOptions:
      version: v1
    type: dynamic
  variables:
  - name: region
    options:
      override:
        type: notallowed
    value: UPDATE_ME
    valueType: text
  - name: name
    options:
      override:
        type: notallowed
    value: $(environment.name)$
    valueType: expression
  - name: engine
    options:
      override:
        type: notallowed
    value: postgres
    valueType: text
  - name: engine_version
    options:
      override:
        type: notallowed
    value: "14"
    valueType: text
  - name: family
    options:
      override:
        type: notallowed
    value: postgres14
    valueType: text
  - name: major_engine_version
    options:
      override:
        type: notallowed
    value: "14"
    valueType: text
  - name: instance_class
    options:
      override:
        restrictedValues:
        - db.t3.micro
        - db.t3.small
        - db.t3.small
        - db.t3.large
        type: restricted
      required: true
    value: db.t3.micro
    valueType: text
  - name: allocated_storage
    options:
      override:
        restrictedValues:
        - "20"
        - "50"
        - "100"
        type: restricted
      required: true
    value: "20"
    valueType: text
  - name: max_allocated_storage
    options:
      override:
        type: notallowed
    value: "100"
    valueType: text
  - name: storage_encrypted
    options:
      override:
        type: notallowed
    value: "false"
    valueType: text
  - name: username
    options:
      override:
        type: allowed
      required: true
    valueType: text
  - name: port
    options:
      override:
        type: notallowed
    value: "5432"
    valueType: text
  - name: multi_az
    options:
      override:
        type: notallowed
    value: "false"
    valueType: text
  - name: maintenance_window
    options:
      override:
        type: notallowed
    value: Mon:00:00-Mon:03:00
    valueType: text
  - name: backup_window
    options:
      override:
        type: notallowed
    value: 03:00-06:00
    valueType: text
  - name: enabled_cloudwatch_logs_exports
    options:
      override:
        type: notallowed
    value: '["postgresql", "upgrade"]'
    valueType: hcl
  - name: create_cloudwatch_log_group
    options:
      override:
        type: notallowed
    value: "true"
    valueType: text
  - name: backup_retention_period
    options:
      override:
        type: notallowed
    value: "1"
    valueType: text
  - name: skip_final_snapshot
    options:
      override:
        type: notallowed
    value: "true"
    valueType: text
  - name: deletion_protection
    options:
      override:
        type: notallowed
    value: "false"
    valueType: text
  - name: performance_insights_enabled
    options:
      override:
        type: notallowed
    value: "true"
    valueType: text
  - name: performance_insights_retention_period
    options:
      override:
        type: notallowed
    value: "7"
    valueType: text
  - name: create_monitoring_role
    options:
      override:
        type: notallowed
    value: "false"
    valueType: text
  - name: monitoring_interval
    options:
      override:
        type: notallowed
    value: "0"
    valueType: text
  - name: parameters
    options:
      override:
        type: notallowed
    value: |-
      [
          {
            name  = "autovacuum"
            value = 1
          },
          {
            name  = "client_encoding"
            value = "utf8"
          }
        ]
    valueType: hcl
  - name: db_subnet_group_name
    options:
      override:
        type: notallowed
    value: UPDATE_ME
    valueType: text
  - name: vpc_security_group_ids
    options:
      override:
        type: notallowed
    value: '["UPDATE_ME"]'
    valueType: hcl
  - name: password
    options:
      override:
        type: allowed
      required: true
    valueType: text
  version: v1
  versionState: active
