apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  description: Create a VPC and Security Group in AWS
  displayName: AWS VPC and Security Group
  name: vpc-and-security-group
  project: madhueaasutility
spec:
  iconURL: https://cdn2.iconfinder.com/data/icons/amazon-aws-stencils/100/Non-Service_Specific_copy_Virtual_Private_CLoud_-512.png
  readme: "## Introduction\n\nUsers can use this template to create a VPC and Security
    Group in AWS \n\n---\n\n## What does this do behind the scenes? \n\nThis template
    will perform the following in a sequence: \n\n1. Create a new VPC in AWS using
    the name of the environment \n2. Create a Security Group within the VPC using
    the name of the environment\n \n\n---\n\n## Defaults and Overrides \nUnless specified,
    the new VPC will be created with the default settings for the AWS region and subnets.
    \ The subnets include private, public and database subnet groups Users have the
    option to override the defaults with alternative options. See the input variables
    section below for complete details. "
  resources:
  - kind: resourcetemplate
    name: rafay-aws-vpc
    resourceOptions:
      version: v1
    type: dynamic
  - dependsOn:
    - name: rafay-aws-vpc
    kind: resourcetemplate
    name: rafay-aws-security-group
    resourceOptions:
      version: v2
    type: dynamic
  variables:
  - name: region
    options:
      override:
        type: allowed
      required: true
    value: us-west-2
    valueType: text
  - name: azs
    options:
      override:
        type: allowed
      required: true
    value: '["us-west-2a","us-west-2b","us-west-2c"]'
    valueType: hcl
  - name: create_database_subnet_group
    options:
      override:
        type: allowed
      required: true
    value: "true"
    valueType: hcl
  - name: public_subnets
    options:
      override:
        type: allowed
      required: true
    value: '["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]'
    valueType: hcl
  - name: private_subnets
    options:
      override:
        type: allowed
      required: true
    value: '["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]'
    valueType: hcl
  - name: database_subnets
    options:
      override:
        type: allowed
      required: true
    value: '["10.0.7.0/24", "10.0.8.0/24", "10.0.9.0/24"]'
    valueType: hcl
  - name: identifier
    options:
      override:
        type: notallowed
      required: true
    value: $(environment.name)$
    valueType: expression
  version: v1
  versionState: active
