apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: rkd-dev-test3
  project: dev-project
spec:
  agents:
  - name: rkd-agent
  secret:
    name: file://artifacts/rkd-dev-test3/sealed-secret.yaml
  template:
    name: app-enviroment-template
    version: v1-rkd
    versionState: draft
  variables:
  - name: cluster_name
    options:
      override:
        type: allowed
      required: true
    value: rkd-dev-test3
    valueType: text
  - name: username
    options:
      override:
        type: allowed
      required: true
    value: rkd@rafay.co
    valueType: text
  - name: aws_access_key_id
    options:
      override:
        type: allowed
      sensitive: true
    value: sealed://variables.2
    valueType: text
  - name: aws_secret_access_key
    options:
      description: tOXv202btw4L2df0Qzbp5C/OMXllvdfULFw5+skq
      override:
        type: allowed
      sensitive: true
    value: sealed://variables.3
    valueType: text
  - name: aws_region
    options:
      override:
        type: allowed
    value: us-west-2
    valueType: text
