##Rafay Project name
projectName: UPDATE_EXISTING_PROJECT_NAME
##Rafay gitops agent name
agentName: eaas-agent
##Rafay respository name
repoName: eaas-repo
##Username to access repository
usernName: UPDATE_REPO_USERNAME
##Token to access repository
token: UPDATE_REPO_TOKEN
##Repository url
endPoint: UPDATE_REPO_ENDPOINT
##Repository revision name
branch: UPDATE_REPO_BRANCH
## Repository path for Rafay to write back configuration.
path: rafay-resources
## Initial Version for Environment Manager resources.
version: v1
## https://docs.rafay.dev/env_manager/overview/
## Environment Manager congifContext Name
## https://docs.rafay.dev/env_manager/templates/contexts/
ConfigContext: aws-101-vpc-ecs
##Environment Manager resourceTemplate Name
## https://docs.rafay.dev/env_manager/templates/resource_templates/
ECSResourceTemplate: 101-vpc-ecs-aws-ecs-rs-tmpl
VPCResourceTemplate: 101-vpc-ecs-aws-vpc-rs-tmpl
## Environment Manager environmentTemplate Name
## https://docs.rafay.dev/env_manager/templates/environment_templates/
EnvironmentTemplate: aws-ecs-vpc-env-tmpl
#Environment: aws-ecs-vpc-env
## Terraform code path 
ECStfRepoPath: terraform/aws/101-vpc-ecs/terraform/ecs
VPCtfRepoPath: terraform/aws/101-vpc-ecs/terraform/vpc
awsRegion: us-west-2
vpcName: em-gs-vpc
