##Rafay Project name
projectName: UPDATE_EXISTING_PROJECT_NAME
##Rafay gitops agent name
agentName: eaas-agent
##Rafay respository name
repoName: eaas-repo
##Username to access repository
usernName: UPDATE_REPO_USERNAME
##Token to access repository
token: UPDATE_REPO_TOKEN
##Repository url
endPoint: UPDATE_REPO_ENDPOINT
##Repository revision name
branch: UPDATE_REPO_BRANCH
## Repository path for Rafay to write back configuration.
path: rafay-resources
## Initial Version for Environment Manager resources.
version: v1
## https://docs.rafay.dev/env_manager/overview/
## Environment Manager congifContext Name
## https://docs.rafay.dev/env_manager/templates/contexts/
RafayConfigContext: rafay
PhoenixNAPConfigContext: phoenixnap
##Environment Manager resourceTemplate Name
## https://docs.rafay.dev/env_manager/templates/resource_templates/
PNAPResourceTemplate: phoenixnap-rs-tmpl
MKSResourceTemplate: rafay-mks-pnap-rs-tmpl
WorkloadResourceTemplate: rafay-workload-rs-tmpl
ProjectResourceTemplate: rafay-project-rs-tmpl
GroupResourceTemplate: rafay-group-rs-tmpl
GroupAssociationResourceTemplate: rafay-group-association-rs-tmpl
RepositoryResourceTemplate: rafay-repository-rs-tmpl
NamespaceResourceTemplate: rafay-namespace-rs-tmpl
AddonResourceTemplate: rafay-addon-rs-tmpl
BlueprintResourceTemplate: rafay-blueprint-rs-tmpl
## Environment Manager environmentTemplate Name
## https://docs.rafay.dev/env_manager/templates/environment_templates/
EnvironmentTemplate: caas-mks-pnap-env-tmpl
## Terraform code path 
PNAPtfRepoPath: terraform/mks/101-caas-pnap/terraform/phoenixnap
MKStfRepoPath: terraform/mks/101-caas-pnap/terraform/mks
WorkloadtfRepoPath: terraform/mks/101-caas-pnap/terraform/workload
ProjecttfRepoPath: terraform/mks/101-caas-pnap/terraform/project
GrouptfRepoPath: terraform/mks/101-caas-pnap/terraform/group
GroupAssociationtfRepoPath: terraform/mks/101-caas-pnap/terraform/group-association
RepositorytfRepoPath: terraform/mks/101-caas-pnap/terraform/repositories
NamespacetfRepoPath: terraform/mks/101-caas-pnap/terraform/namespace
AddontfRepoPath: terraform/mks/101-caas-pnap/terraform/addon
BlueprinttfRepoPath: terraform/mks/101-caas-pnap/terraform/blueprints
