version: '3.4'
services:
  qdrant:
    image: qdrant/qdrant:v1.3.0
    restart: on-failure
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - rag
  api:
    container_name: fastapi_server
    build: backend/.
    command: "uvicorn server:app --host 0.0.0.0 --port 8082"
    ports:
      - "8082:8082"
    environment:
      - OPEN_AI_SECRET_PREFIX=OPEN_AI_KEY
      - QDRANT_URL=http://qdrant:6333
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - rag
  app:
    container_name: streamlit_app
    build: frontend/.
    command: "streamlit run --server.port 80 --server.enableCORS false Information.py"
    environment:
      - BACKEND_URL=http://fastapi_server:8082
    ports:
      - "8081:80"
    networks:
      - rag

networks:
  rag:
