apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eaas-repo-madhu-utility-madhueaasutility
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBW31OjR1KqPR1AF8JR0+L6z8cVsmnnv+ip+XNTsxqABQ/D64inkuL99+pyINT1NjqWlcUtfdP66EkZ0MP+0H+BH60tfwWtKjDKj1iQJbSq14DMzEXzL1boLLsnjUo+6UKPYvP7Ir7HKx+5DlGXNo01/wEZgm88EYkB66RcQdNBK1PfrP0A6jmfhKyT/t6lMzBX8xf2NKYXcwIe96zwztQckCbgb8cK/ZmGRPPtiOJYfK8XmX7N6CZqXynt6FWV5Li3wboTjTo1AMfPdXv7nUGHftBF3Bq9W3tcgUk7VGF0QoRXeBLAZ9VjdU3RvgRpDRgpTLzCgLWh2DXoJlsVvzfjzqoaFbND6uvsbr6tT2+FUfueut+xZYVmSV6nRNfC91W52SuhJ4oIL9+z+q6RMMBzz2/kX9HNCZA=
  template:
    metadata:
      creationTimestamp: null
      name: eaas-repo-madhu-utility-madhueaasutility
      namespace: default

