##Rafay Project name
projectName: UPDATE_EXISTING_PROJECT_NAME
## Initial Version for Environment Manager resources.
version: v1
## https://docs.rafay.dev/env_manager/overview/
## Environment Manager congifContext Name
## https://docs.rafay.dev/env_manager/templates/contexts/
RafayConfigContext: rafay-101-caas-eks
AWSConfigContext: aws-101-caas-eks
##Environment Manager resourceTemplate Name
## https://docs.rafay.dev/env_manager/templates/resource_templates/
ProjectResourceTemplate: 101-caas-eks-rafay-project-rs-tmpl
GroupResourceTemplate: 101-caas-eks-rafay-group-rs-tmpl
GroupAssociationResourceTemplate: 101-caas-eks-rafay-group-association-rs-tmpl
RepositoryResourceTemplate: 101-caas-eks-rafay-repository-rs-tmpl
NamespaceResourceTemplate: 101-caas-eks-rafay-namespace-rs-tmpl
EKSCloudCredentialResourceTemplate: 101-caas-eks-rafay-ekscloudcredential-rs-tmpl
AddonResourceTemplate: 101-caas-eks-rafay-addon-rs-tmpl
BlueprintResourceTemplate: 101-caas-eks-rafay-blueprint-rs-tmpl
EKSResourceTemplate: 101-caas-eks-rafay-eks-rs-tmpl
## Environment Manager environmentTemplate Name
## https://docs.rafay.dev/env_manager/templates/environment_templates/
EnvironmentTemplate: caas-eks-env-tmpl
## Terraform code path 
ProjecttfRepoPath: terraform/aws/101-caas-eks/terraform/project
GrouptfRepoPath: terraform/aws/101-caas-eks/terraform/group
GroupAssociationtfRepoPath: terraform/aws/101-caas-eks/terraform/group-association
RepositorytfRepoPath: terraform/aws/101-caas-eks/terraform/repositories
NamespacetfRepoPath: terraform/aws/101-caas-eks/terraform/namespace
EKSCloudCredentialtfRepoPath: terraform/aws/101-caas-eks/terraform/cloud-credentials-eks
AddontfRepoPath: terraform/aws/101-caas-eks/terraform/addon
BlueprinttfRepoPath: terraform/aws/101-caas-eks/terraform/blueprints
EKStfRepoPath: terraform/aws/101-caas-eks/terraform/eks
