{{ if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docker-compose-django-celery-redis-postgres-default
  labels:
  {{- include "django-app.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/docker-compose-django-celery-redis-postgres-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/docker-compose-django-celery-redis-postgres-default: "true"
{{ end }}
