apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    service: nginx
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.type }}
  selector:
    service: nginx
    {{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.nginx.ports | toYaml | nindent 2 }}