apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    service: redis
  {{- include "django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    service: redis
  {{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.redis.ports | toYaml | nindent 2 -}}