apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
  labels:
    io.kompose.service: static-volume
  {{- include "django-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.staticVolume.storageRequest | quote }}