apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rkd-dev-test-nov14
  namespace: default
spec:
  encryptedData:
    variables.2: AQDFkx4xAPBvWtBfeY/6k3sFm4WcQxaAjZyNTtYbKarynriy3r8bD/T+IzBqAr9iTCetYh//ER73iUklRgF3iwCs/emzb8a4oLUpTviSi8mcQ7G2SElIxKo4q1Pvcx8LVvMYvC4fFfCHzeiFb7ntE9iXoxGmFqHjUnyIQqfQVmu5lL+lvwyDtmFN0YwTs/fvbqkeD6FyflTWpBT2az6rcugiQAH/bLXlJEgxaVKFzHMmLKU+malMR7IGLF7L+S3nCajR2F5RyAuLF8bf7JffaGAWb4p7JWrBJ60KE49Z1MHzyaDKTdV5LsS4K9yNjS72orybaujTtHfRDybjRSxazmMAWOH9hHj1D4LQJgZu+bi7pBxE+WYddRsorxA+TXJy3HAbApzB
    variables.3: AQA62l0lDAikwvM95vgPSujZOHcKv7h+CeSX1CJu92gxhunE90PBQcrImc6Nm3HxGjsveFVa/3rKVQG7Y72HL+jFwwWX08JlUgqj5TxKRbNt6OmSV/GIqwr4DrWrjOX6ynTNsfPhrDGnUCwxWwnTubq3Um2iN2s4C1VeQgitKpVQcRCw74lXGnocG/CcHsy5KOwssQUTucgwuExbrlHClmg3iWYYZ3Ou+01T2DoOl4d3mknHL3bL+0wOAp9dHBWWtupR1mdqSZzrHbJ3DNpT+vvp1Rq0p5LijK/ExSzW2qIxbMSkYBxlqho2BzwrJzWOMc6z2vJPE7hnZGC5I67fOPTWnNnbjJtLtlcayxqmIsbq/3Wx4JAtUFnLbFeWaNhorzaeG1Dx8Xz+o6p2FgQcH9mhCICBp1s2XfI=
  template:
    metadata:
      creationTimestamp: null
      name: rkd-dev-test-nov14
      namespace: default

