apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: 101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: aws-101-vpc-ecs-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/aws/101-vpc-ecs/terraform/vpc
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: aws_region
    options:
      override:
        type: allowed
      required: true
    value: us-west-2
    valueType: text
  - name: vpc_name
    options:
      override:
        type: allowed
      required: true
    value: em-gs-vpc-madhueaasutility
    valueType: text
  version: v1
  versionState: active
