apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: 101-vpc-ecs-aws-ecs-rs-tmpl-madhueaasutility
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: aws-101-vpc-ecs-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/aws/101-vpc-ecs/terraform/ecs
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: vpc_name
    options:
      description: Name of the VPC
      override:
        type: notallowed
    value: $(resource."101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility".output.vpc_name.value)$
    valueType: expression
  - name: vpc_id
    options:
      description: ID of the VPC
      override:
        type: notallowed
    value: $(resource."101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility".output.vpc_id.value)$
    valueType: expression
  - name: aws_region
    options:
      description: AWS Region
      override:
        type: notallowed
    value: $(resource."101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility".output.region.value)$
    valueType: expression
  - name: subnet_id
    options:
      description: Subnet ID for ECS Service
      override:
        type: notallowed
    value: $(resource."101-vpc-ecs-aws-vpc-rs-tmpl-madhueaasutility".output.public_subnets.value[0])$
    valueType: expression
  version: v1
  versionState: active
