apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: aws-vpc-ec2-rs-tmpl-madhueaasutility
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: aws-101-vpc-ec2-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/aws/101-vpc-ec2/terraform
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: aws_region
    options:
      override:
        type: allowed
      required: true
    value: us-west-2
    valueType: text
  version: v1
  versionState: active
