apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: gcp-vnet-vm-rs-tmpl-madhueaasutility
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: gcp-101-vpc-instance-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      useSystemStateStore: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/gcp/101-vpc-instance/terraform
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: region
    options:
      override:
        type: allowed
      required: true
    value: us-central1
    valueType: text
  - name: zone
    options:
      override:
        type: allowed
      required: true
    value: us-central1-a
    valueType: text
  - name: project_id
    options:
      override:
        type: allowed
      required: true
    value: UPDATE_PROJECT_ID
    valueType: text
  version: v1
  versionState: active
