apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-iam-service-accounts-eks
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-iam/modules
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create_role
    options:
      description: Whether to create a role
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: role_name
    options:
      description: Name of IAM role
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: role_path
    options:
      description: Path of IAM role
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: role_permissions_boundary_arn
    options:
      description: Permissions boundary ARN to use for IAM role
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: role_description
    options:
      description: IAM Role description
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: role_name_prefix
    options:
      description: IAM role name prefix
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: policy_name_prefix
    options:
      description: IAM policy name prefix
      override:
        type: allowed
    value: '"AmazonEKS_"'
    valueType: hcl
  - name: role_policy_arns
    options:
      description: ARNs of any policies to attach to the IAM role
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: oidc_providers
    options:
      description: Map of OIDC providers where each provider map should contain the
        `provider_arn` and `namespace_service_accounts`
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add the the IAM role
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: force_detach_policies
    options:
      description: Whether policies should be detached from this role when destroying
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: max_session_duration
    options:
      description: Maximum CLI/API session duration in seconds between 3600 and 43200
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: assume_role_condition_test
    options:
      description: Name of the [IAM condition operator](https//docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html)
        to evaluate when assuming the role
      override:
        type: allowed
    value: '"StringEquals"'
    valueType: hcl
  - name: allow_self_assume_role
    options:
      description: Determines whether to allow the role to be [assume itself](https//aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/)
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_aws_gateway_controller_policy
    options:
      description: Determines whether to attach the AWS Gateway Controller IAM policy
        to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_cert_manager_policy
    options:
      description: Determines whether to attach the Cert Manager IAM policy to the
        role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: cert_manager_hosted_zone_arns
    options:
      description: Route53 hosted zone ARNs to allow Cert manager to manage records
      override:
        type: allowed
    value: '["arn:aws:route53:::hostedzone/*"]'
    valueType: hcl
  - name: attach_cluster_autoscaler_policy
    options:
      description: Determines whether to attach the Cluster Autoscaler IAM policy
        to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: cluster_autoscaler_cluster_ids
    options:
      description: Deprecated - use `cluster_autoscaler_cluster_names` List of cluster
        names to appropriately scope permissions within the Cluster Autoscaler IAM
        policy
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: cluster_autoscaler_cluster_names
    options:
      description: List of cluster names to appropriately scope permissions within
        the Cluster Autoscaler IAM policy
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: attach_ebs_csi_policy
    options:
      description: Determines whether to attach the EBS CSI IAM policy to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: ebs_csi_kms_cmk_ids
    options:
      description: KMS CMK IDs to allow EBS CSI to manage encrypted volumes
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: attach_efs_csi_policy
    options:
      description: Determines whether to attach the EFS CSI IAM policy to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_mountpoint_s3_csi_policy
    options:
      description: Determines whether to attach the Mountpoint S3 CSI IAM policy to
        the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: mountpoint_s3_csi_bucket_arns
    options:
      description: S3 bucket ARNs to allow Mountpoint S3 CSI to list buckets
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: mountpoint_s3_csi_path_arns
    options:
      description: S3 path ARNs to allow Mountpoint S3 CSI driver to manage items
        at the provided path(s). This is required if `attach_mountpoint_s3_csi_policy
        = true`
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: attach_external_dns_policy
    options:
      description: Determines whether to attach the External DNS IAM policy to the
        role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: external_dns_hosted_zone_arns
    options:
      description: Route53 hosted zone ARNs to allow External DNS to manage records
      override:
        type: allowed
    value: '["arn:aws:route53:::hostedzone/*"]'
    valueType: hcl
  - name: attach_external_secrets_policy
    options:
      description: Determines whether to attach the External Secrets policy to the
        role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: external_secrets_ssm_parameter_arns
    options:
      description: List of Systems Manager Parameter ARNs that contain secrets to
        mount using External Secrets
      override:
        type: allowed
    value: '["arn:aws:ssm:*:*:parameter/*"]'
    valueType: hcl
  - name: external_secrets_secrets_manager_arns
    options:
      description: List of Secrets Manager ARNs that contain secrets to mount using
        External Secrets
      override:
        type: allowed
    value: '["arn:aws:secretsmanager:*:*:secret:*"]'
    valueType: hcl
  - name: external_secrets_kms_key_arns
    options:
      description: List of KMS Key ARNs that are used by Secrets Manager that contain
        secrets to mount using External Secrets
      override:
        type: allowed
    value: '["arn:aws:kms:*:*:key/*"]'
    valueType: hcl
  - name: external_secrets_secrets_manager_create_permission
    options:
      description: Determins whether External Secrets may use secretsmanagerCreateSecret
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_fsx_lustre_csi_policy
    options:
      description: Determines whether to attach the FSx for Lustre CSI Driver IAM
        policy to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: fsx_lustre_csi_service_role_arns
    options:
      description: Service role ARNs to allow FSx for Lustre CSI create and manage
        FSX for Lustre service linked roles
      override:
        type: allowed
    value: '["arn:aws:iam::*:role/aws-service-role/s3.data-source.lustre.fsx.amazonaws.com/*"]'
    valueType: hcl
  - name: attach_karpenter_controller_policy
    options:
      description: Determines whether to attach the Karpenter Controller policy to
        the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: karpenter_controller_cluster_id
    options:
      description: Deprecated - use `karpenter_controller_cluster_name` The name of
        the cluster where the Karpenter controller is provisioned/managing
      override:
        type: allowed
    value: '"*"'
    valueType: hcl
  - name: karpenter_controller_cluster_name
    options:
      description: The name of the cluster where the Karpenter controller is provisioned/managing
      override:
        type: allowed
    value: '"*"'
    valueType: hcl
  - name: karpenter_tag_key
    options:
      description: Tag key key = value applied to resources launched by Karpenter
        through the Karpenter provisioner
      override:
        type: allowed
    value: karpenter.sh/discovery
    valueType: hcl
  - name: karpenter_controller_ssm_parameter_arns
    options:
      description: List of SSM Parameter ARNs that contain AMI IDs launched by Karpenter
      override:
        type: allowed
    value: '["arn:aws:ssm:*:*:parameter/aws/service/*"]'
    valueType: hcl
  - name: karpenter_controller_node_iam_role_arns
    options:
      description: List of node IAM role ARNs Karpenter can use to launch nodes
      override:
        type: allowed
    value: '["*"]'
    valueType: hcl
  - name: karpenter_subnet_account_id
    options:
      description: Account ID of where the subnets Karpenter will utilize resides.
        Used when subnets are shared from another account
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: karpenter_sqs_queue_arn
    options:
      description: (Optional) ARN of SQS used by Karpenter when native node termination
        handling is enabled
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: enable_karpenter_instance_profile_creation
    options:
      description: Determines whether Karpenter will be allowed to create the IAM
        instance profile (v1beta1/v0.32+)
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_load_balancer_controller_policy
    options:
      description: Determines whether to attach the Load Balancer Controller policy
        to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_load_balancer_controller_targetgroup_binding_only_policy
    options:
      description: Determines whether to attach the Load Balancer Controller policy
        for the TargetGroupBinding only
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: load_balancer_controller_targetgroup_arns
    options:
      description: List of Target groups ARNs using Load Balancer Controller
      override:
        type: allowed
    value: '["arn:aws:elasticloadbalancing:*:*:targetgroup/*/*"]'
    valueType: hcl
  - name: attach_appmesh_controller_policy
    options:
      description: Determines whether to attach the Appmesh Controller policy to the
        role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_appmesh_envoy_proxy_policy
    options:
      description: Determines whether to attach the Appmesh envoy proxy policy to
        the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_amazon_managed_service_prometheus_policy
    options:
      description: Determines whether to attach the Amazon Managed Service for Prometheus
        IAM policy to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: amazon_managed_service_prometheus_workspace_arns
    options:
      description: List of AMP Workspace ARNs to read and write metrics
      override:
        type: allowed
    value: '["*"]'
    valueType: hcl
  - name: attach_velero_policy
    options:
      description: Determines whether to attach the Velero IAM policy to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: velero_s3_bucket_arns
    options:
      description: List of S3 Bucket ARNs that Velero needs access to in order to
        backup and restore cluster resources
      override:
        type: allowed
    value: '["*"]'
    valueType: hcl
  - name: attach_vpc_cni_policy
    options:
      description: Determines whether to attach the VPC CNI IAM policy to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: vpc_cni_enable_ipv4
    options:
      description: Determines whether to enable IPv4 permissions for VPC CNI policy
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: vpc_cni_enable_ipv6
    options:
      description: Determines whether to enable IPv6 permissions for VPC CNI policy
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: attach_node_termination_handler_policy
    options:
      description: Determines whether to attach the Node Termination Handler policy
        to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: node_termination_handler_sqs_queue_arns
    options:
      description: List of SQS ARNs that contain node termination events
      override:
        type: allowed
    value: '["*"]'
    valueType: hcl
  - name: attach_cloudwatch_observability_policy
    options:
      description: Determines whether to attach the Amazon CloudWatch Observability
        IAM policies to the role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  version: v1
  versionState: active
