apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-eks-karpenter
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-eks
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create
    options:
      description: Controls if resources should be created (affects nearly all resources)
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add to all resources
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: cluster_name
    options:
      description: The name of the EKS cluster
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: create_iam_role
    options:
      description: Determines whether an IAM role is created
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: iam_role_name
    options:
      description: Name of the IAM role
      override:
        type: allowed
    value: '"KarpenterController"'
    valueType: hcl
  - name: iam_role_use_name_prefix
    options:
      description: Determines whether the name of the IAM role (`iam_role_name`) is
        used as a prefix
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: iam_role_path
    options:
      description: Path of the IAM role
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: iam_role_description
    options:
      description: IAM role description
      override:
        type: allowed
    value: '"Karpenter controller IAM role"'
    valueType: hcl
  - name: iam_role_max_session_duration
    options:
      description: Maximum API session duration in seconds between 3600 and 43200
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: iam_role_permissions_boundary_arn
    options:
      description: Permissions boundary ARN to use for the IAM role
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: iam_role_tags
    options:
      description: A map of additional tags to add the the IAM role
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: iam_policy_name
    options:
      description: Name of the IAM policy
      override:
        type: allowed
    value: '"KarpenterController"'
    valueType: hcl
  - name: iam_policy_use_name_prefix
    options:
      description: Determines whether the name of the IAM policy (`iam_policy_name`)
        is used as a prefix
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: iam_policy_path
    options:
      description: Path of the IAM policy
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: iam_policy_description
    options:
      description: IAM policy description
      override:
        type: allowed
    value: '"Karpenter controller IAM policy"'
    valueType: hcl
  - name: iam_role_policies
    options:
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: ami_id_ssm_parameter_arns
    options:
      description: List of SSM Parameter ARNs that Karpenter controller is allowed
        read access (for retrieving AMI IDs)
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: enable_pod_identity
    options:
      description: Determines whether to enable support for EKS pod identity
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: enable_irsa
    options:
      description: Determines whether to enable support for IAM role for service accounts
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: irsa_oidc_provider_arn
    options:
      description: OIDC provider arn used in trust policy for IAM role for service
        accounts
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: irsa_namespace_service_accounts
    options:
      description: List of `namespaceserviceaccount`pairs to use in trust policy for
        IAM role for service accounts
      override:
        type: allowed
    value: '["karpenter:karpenter"]'
    valueType: hcl
  - name: irsa_assume_role_condition_test
    options:
      description: Name of the [IAM condition operator](https//docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html)
        to evaluate when assuming the role
      override:
        type: allowed
    value: '"StringEquals"'
    valueType: hcl
  - name: create_pod_identity_association
    options:
      description: Determines whether to create pod identity association
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: namespace
    options:
      description: Namespace to associate with the Karpenter Pod Identity
      override:
        type: allowed
    value: '"kube-system"'
    valueType: hcl
  - name: service_account
    options:
      description: Service account to associate with the Karpenter Pod Identity
      override:
        type: allowed
    value: '"karpenter"'
    valueType: hcl
  - name: enable_spot_termination
    options:
      description: Determines whether to enable native spot termination handling
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: queue_name
    options:
      description: Name of the SQS queue
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: queue_managed_sse_enabled
    options:
      description: Boolean to enable server-side encryption (SSE) of message content
        with SQS-owned encryption keys
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: queue_kms_master_key_id
    options:
      description: The ID of an AWS-managed customer master key (CMK) for Amazon SQS
        or a custom CMK
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: queue_kms_data_key_reuse_period_seconds
    options:
      description: The length of time, in seconds, for which Amazon SQS can reuse
        a data key to encrypt or decrypt messages before calling AWS KMS again
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: create_node_iam_role
    options:
      description: Determines whether an IAM role is created or to use an existing
        IAM role
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: cluster_ip_family
    options:
      description: The IP family used to assign Kubernetes pod and service addresses.
        Valid values are `ipv4` (default) and `ipv6`. Note If `ipv6` is specified,
        the `AmazonEKS_CNI_IPv6_Policy` must exist in the account. This policy is
        created by the EKS module with `create_cni_ipv6_iam_policy = true`
      override:
        type: allowed
    value: '"ipv4"'
    valueType: hcl
  - name: node_iam_role_arn
    options:
      description: Existing IAM role ARN for the IAM instance profile. Required if
        `create_iam_role` is set to `false`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: node_iam_role_name
    options:
      description: Name to use on IAM role created
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: node_iam_role_use_name_prefix
    options:
      description: Determines whether the IAM role name (`iam_role_name`) is used
        as a prefix
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: node_iam_role_path
    options:
      description: IAM role path
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: node_iam_role_description
    options:
      description: Description of the role
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: node_iam_role_max_session_duration
    options:
      description: Maximum API session duration in seconds between 3600 and 43200
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: node_iam_role_permissions_boundary
    options:
      description: ARN of the policy that is used to set the permissions boundary
        for the IAM role
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: node_iam_role_attach_cni_policy
    options:
      description: Whether to attach the `AmazonEKS_CNI_Policy`/`AmazonEKS_CNI_IPv6_Policy`
        IAM policy to the IAM IAM role. WARNING If set `false` the permissions must
        be assigned to the `aws-node` DaemonSet pods via another method or nodes will
        not be able to join the cluster
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: node_iam_role_additional_policies
    options:
      description: Additional policies to be added to the IAM role
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: node_iam_role_tags
    options:
      description: A map of additional tags to add to the IAM role created
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: create_access_entry
    options:
      description: Determines whether an access entry is created for the IAM role
        used by the node IAM role
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: access_entry_type
    options:
      description: Type of the access entry. `EC2_LINUX`, `FARGATE_LINUX`, or `EC2_WINDOWS`;
        defaults to `EC2_LINUX`
      override:
        type: allowed
    value: '"EC2_LINUX"'
    valueType: hcl
  - name: create_instance_profile
    options:
      description: Whether to create an IAM instance profile
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: rule_name_prefix
    options:
      description: Prefix used for all event bridge rules
      override:
        type: allowed
    value: '"Karpenter"'
    valueType: hcl
  version: v1
  versionState: active
