apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-efs
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-efs
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create
    options:
      description: Determines whether resources will be created (affects all resources)
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: name
    options:
      description: The name of the file system
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add to all resources
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: availability_zone_name
    options:
      description: The AWS Availability Zone in which to create the file system. Used
        to create a file system that uses One Zone storage classes
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: creation_token
    options:
      description: A unique name (a maximum of 64 characters are allowed) used as
        reference when creating the Elastic File System to ensure idempotent file
        system creation. By default generated by Terraform
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: performance_mode
    options:
      description: The file system performance mode. Can be either `generalPurpose`
        or `maxIO`. Default is `generalPurpose`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: encrypted
    options:
      description: If `true`, the disk will be encrypted
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: kms_key_arn
    options:
      description: The ARN for the KMS encryption key. When specifying `kms_key_arn`,
        encrypted needs to be set to `true`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: provisioned_throughput_in_mibps
    options:
      description: The throughput, measured in MiB/s, that you want to provision for
        the file system. Only applicable with `throughput_mode` set to `provisioned`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: throughput_mode
    options:
      description: Throughput mode for the file system. Defaults to `bursting`. Valid
        values `bursting`, `elastic`, and `provisioned`. When using `provisioned`,
        also set `provisioned_throughput_in_mibps`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: lifecycle_policy
    options:
      description: A file system [lifecycle policy](https//docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html)
        object
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: attach_policy
    options:
      description: Determines whether a policy is attached to the file system
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: bypass_policy_lockout_safety_check
    options:
      description: A flag to indicate whether to bypass the `aws_efs_file_system_policy`
        lockout safety check. Defaults to `false`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: source_policy_documents
    options:
      description: List of IAM policy documents that are merged together into the
        exported document. Statements must have unique `sid`s
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: override_policy_documents
    options:
      description: List of IAM policy documents that are merged together into the
        exported document. In merging, statements with non-blank `sid`s will override
        statements with the same `sid`
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: policy_statements
    options:
      description: A list of IAM policy [statements](https//registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement)
        for custom permission usage
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: deny_nonsecure_transport
    options:
      description: Determines whether `awsSecureTransport` is required when connecting
        to elastic file system
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: mount_targets
    options:
      description: A map of mount target definitions to create
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: create_security_group
    options:
      description: Determines whether a security group is created
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: security_group_name
    options:
      description: Name to assign to the security group. If omitted, Terraform will
        assign a random, unique name
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: security_group_description
    options:
      description: Security group description. Defaults to Managed by Terraform
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: security_group_use_name_prefix
    options:
      description: Determines whether to use a name prefix for the security group.
        If `true`, the `security_group_name` value will be used as a prefix
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: security_group_vpc_id
    options:
      description: The VPC ID where the security group will be created
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: security_group_rules
    options:
      description: Map of security group rule definitions to create
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: access_points
    options:
      description: A map of access point definitions to create
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: create_backup_policy
    options:
      description: Determines whether a backup policy is created
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: enable_backup_policy
    options:
      description: Determines whether a backup policy is `ENABLED` or `DISABLED`
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: create_replication_configuration
    options:
      description: Determines whether a replication configuration is created
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: replication_configuration_destination
    options:
      description: A destination configuration block
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
