apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-lambda-alias
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-eks
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create
    options:
      description: Controls whether resources should be created
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: use_existing_alias
    options:
      description: Whether to manage existing alias instead of creating a new one.
        Useful when using this module together with external tool do deployments (eg,
        AWS CodeDeploy).
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: refresh_alias
    options:
      description: Whether to refresh function version used in the alias. Useful when
        using this module together with external tool do deployments (eg, AWS CodeDeploy).
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: create_async_event_config
    options:
      description: Controls whether async event configuration for Lambda Function/Alias
        should be created
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: create_version_async_event_config
    options:
      description: Whether to allow async event configuration on version of Lambda
        Function used by alias (this will revoke permissions from previous version
        because Terraform manages only current resources)
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: create_qualified_alias_async_event_config
    options:
      description: Whether to allow async event configuration on qualified alias
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: create_version_allowed_triggers
    options:
      description: Whether to allow triggers on version of Lambda Function used by
        alias (this will revoke permissions from previous version because Terraform
        manages only current resources)
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: create_qualified_alias_allowed_triggers
    options:
      description: Whether to allow triggers on qualified alias
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: name
    options:
      description: Name for the alias you are creating.
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: description
    options:
      description: Description of the alias.
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: function_name
    options:
      description: The function ARN of the Lambda function for which you want to create
        an alias.
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: function_version
    options:
      description: Lambda function version for which you are creating the alias. Pattern
        ($LATEST|[0-9]+).
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: routing_additional_version_weights
    options:
      description: A map that defines the proportion of events that should be sent
        to different versions of a lambda function.
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: maximum_event_age_in_seconds
    options:
      description: Maximum age of a request that Lambda sends to a function for processing
        in seconds. Valid values between 60 and 21600.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: maximum_retry_attempts
    options:
      description: Maximum number of times to retry when the function returns an error.
        Valid values between 0 and 2. Defaults to 2.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: destination_on_failure
    options:
      description: Amazon Resource Name (ARN) of the destination resource for failed
        asynchronous invocations
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: destination_on_success
    options:
      description: Amazon Resource Name (ARN) of the destination resource for successful
        asynchronous invocations
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: allowed_triggers
    options:
      description: Map of allowed triggers to create Lambda permissions
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: event_source_mapping
    options:
      description: Map of event source mapping
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
