apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-lambda-docker
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-eks
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create_ecr_repo
    options:
      description: Controls whether ECR repository for Lambda image should be created
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: create_sam_metadata
    options:
      description: Controls whether the SAM metadata null resource should be created
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: use_image_tag
    options:
      description: Controls whether to use image tag in ECR repository URI or not.
        Disable this to deploy latest image using ID (sha256...)
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: ecr_address
    options:
      description: Address of ECR repository for cross-account container image pulling
        (optional). Option `create_ecr_repo` must be `false`
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: ecr_repo
    options:
      description: Name of ECR repository to use or to create
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: image_tag
    options:
      description: Image tag to use. If not specified current timestamp in format
        'YYYYMMDDhhmmss' will be used. This can lead to unnecessary rebuilds.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: source_path
    options:
      description: Path to folder containing application code
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: docker_file_path
    options:
      description: Path to Dockerfile in source package
      override:
        type: allowed
    value: '"Dockerfile"'
    valueType: hcl
  - name: image_tag_mutability
    options:
      description: The tag mutability setting for the repository. Must be one of `MUTABLE`
        or `IMMUTABLE`
      override:
        type: allowed
    value: '"MUTABLE"'
    valueType: hcl
  - name: scan_on_push
    options:
      description: Indicates whether images are scanned after being pushed to the
        repository
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: ecr_force_delete
    options:
      description: If true, will delete the repository even if it contains images.
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: ecr_repo_tags
    options:
      description: A map of tags to assign to ECR repository
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: build_args
    options:
      description: A map of Docker build arguments.
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: ecr_repo_lifecycle_policy
    options:
      description: A JSON formatted ECR lifecycle policy to automate the cleaning
        up of unused images.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: keep_remotely
    options:
      description: Whether to keep Docker image in the remote registry on destroy
        operation.
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: platform
    options:
      description: The target architecture platform to build the image for.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: force_remove
    options:
      description: Whether to remove image forcibly when the resource is destroyed.
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: keep_locally
    options:
      description: Whether to delete the Docker image locally on destroy operation.
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: triggers
    options:
      description: A map of arbitrary strings that, when changed, will force the docker_image
        resource to be replaced. This can be used to rebuild an image when contents
        of source code folders change
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
