apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-route53-records
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-route53-records
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create
    options:
      description: Whether to create DNS records
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: zone_id
    options:
      description: ID of DNS zone
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: zone_name
    options:
      description: Name of DNS zone
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: private_zone
    options:
      description: Whether Route53 zone is private or public
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: records
    options:
      description: List of objects of DNS records
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: records_jsonencoded
    options:
      description: List of map of DNS records (stored as jsonencoded string, for terragrunt)
      override:
        type: allowed
    value: "null"
    valueType: hcl
  version: v1
  versionState: active
