apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-eks-user-data
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-eks
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create
    options:
      description: Determines whether to create user-data or not
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: platform
    options:
      description: DEPRECATED - use `ami_type` instead. Will be removed in `v21.0`
        Identifies the OS platform as `bottlerocket`, `linux` (AL2), `al2023`, or
        `windows`
      override:
        type: allowed
    value: '"linux"'
    valueType: hcl
  - name: ami_type
    options:
      description: Type of Amazon Machine Image (AMI) associated with the EKS Node
        Group. See the [AWS documentation](https//docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html#AmazonEKS-Type-Nodegroup-amiType)
        for valid values
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: enable_bootstrap_user_data
    options:
      description: Determines whether the bootstrap configurations are populated within
        the user data template
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: is_eks_managed_node_group
    options:
      description: Determines whether the user data is used on nodes in an EKS managed
        node group. Used to determine if user data will be appended or not
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: cluster_name
    options:
      description: Name of the EKS cluster
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: cluster_endpoint
    options:
      description: Endpoint of associated EKS cluster
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: cluster_auth_base64
    options:
      description: Base64 encoded CA of associated EKS cluster
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: cluster_service_cidr
    options:
      description: The CIDR block (IPv4 or IPv6) used by the cluster to assign Kubernetes
        service IP addresses. This is derived from the cluster itself
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: cluster_ip_family
    options:
      description: The IP family used to assign Kubernetes pod and service addresses.
        Valid values are `ipv4` (default) and `ipv6`
      override:
        type: allowed
    value: '"ipv4"'
    valueType: hcl
  - name: additional_cluster_dns_ips
    options:
      description: Additional DNS IP addresses to use for the cluster. Only used when
        `ami_type` = `BOTTLEROCKET_*`
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: cluster_service_ipv4_cidr
    options:
      description: Deprecated The CIDR block to assign Kubernetes service IP addresses
        from. If you don't specify a block, Kubernetes assigns addresses from either
        the 10.100.0.0/16 or 172.20.0.0/16 CIDR blocks
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: pre_bootstrap_user_data
    options:
      description: User data that is injected into the user data script ahead of the
        EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: post_bootstrap_user_data
    options:
      description: User data that is appended to the user data script after of the
        EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: bootstrap_extra_args
    options:
      description: Additional arguments passed to the bootstrap script. When `ami_type`
        = `BOTTLEROCKET_*`; these are additional [settings](https//github.com/bottlerocket-os/bottlerocket#settings)
        that are provided to the Bottlerocket user data
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: user_data_template_path
    options:
      description: Path to a local, custom user data template file to use when rendering
        user data
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: cloudinit_pre_nodeadm
    options:
      description: Array of cloud-init document parts that are created before the
        nodeadm document part
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: cloudinit_post_nodeadm
    options:
      description: Array of cloud-init document parts that are created after the nodeadm
        document part
      override:
        type: allowed
    value: '""'
    valueType: hcl
  version: v1
  versionState: active
