apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-iam-account
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-iam/modules
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: get_caller_identity
    options:
      description: Whether to get AWS account ID, User ID, and ARN in which Terraform
        is authorized
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: account_alias
    options:
      description: AWS IAM account alias for this account
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: create_account_password_policy
    options:
      description: Whether to create AWS IAM account password policy
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: max_password_age
    options:
      description: The number of days that an user password is valid.
      override:
        type: allowed
    value: "0.0"
    valueType: hcl
  - name: minimum_password_length
    options:
      description: Minimum length to require for user passwords
      override:
        type: allowed
    value: "8.0"
    valueType: hcl
  - name: allow_users_to_change_password
    options:
      description: Whether to allow users to change their own password
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: hard_expiry
    options:
      description: Whether users are prevented from setting a new password after their
        password has expired (i.e. require administrator reset)
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: password_reuse_prevention
    options:
      description: The number of previous passwords that users are prevented from
        reusing
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: require_lowercase_characters
    options:
      description: Whether to require lowercase characters for user passwords
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: require_uppercase_characters
    options:
      description: Whether to require uppercase characters for user passwords
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: require_numbers
    options:
      description: Whether to require numbers for user passwords
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: require_symbols
    options:
      description: Whether to require symbols for user passwords
      override:
        type: allowed
    value: "true"
    valueType: hcl
  version: v1
  versionState: active
