apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-iam-policy
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-iam/modules
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create_policy
    options:
      description: Whether to create the IAM policy
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: name
    options:
      description: The name of the policy
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: name_prefix
    options:
      description: IAM policy name prefix
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: path
    options:
      description: The path of the policy in IAM
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: description
    options:
      description: The description of the policy
      override:
        type: allowed
    value: '"IAM Policy"'
    valueType: hcl
  - name: policy
    options:
      description: The path of the policy in IAM (tpl file)
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add to all resources.
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
