apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-iam-group-with-assumable-roles-policy
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-iam/modules
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: name
    options:
      description: Name of IAM policy and IAM group
      override:
        type: allowed
    value: $("em-iam-\(environment.name)")$
    valueType: expression
  - name: path
    options:
      description: Path of IAM policy and IAM group
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: assumable_roles
    options:
      description: List of IAM roles ARNs which can be assumed by the group
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: assumable_roles_policy_name_suffix
    options:
      description: Append this name to the policy name that will be created for assuming
        the given roles (default null -- the policy name will be group name)
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: group_users
    options:
      description: List of IAM users to have in an IAM group which can assume the
        role
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add to all resources.
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
