apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-iam-read-only-policy
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-iam/modules
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create_policy
    options:
      description: Whether to create the IAM policy
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: name
    options:
      description: The name of the policy
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: name_prefix
    options:
      description: IAM policy name prefix
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: path
    options:
      description: The path of the policy in IAM
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: description
    options:
      description: The description of the policy
      override:
        type: allowed
    value: '"IAM Policy"'
    valueType: hcl
  - name: allowed_services
    options:
      description: List of services to allow Get/List/Describe/View options. Service
        name should be the same as corresponding service IAM prefix. See what it is
        for each service here https//docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: additional_policy_json
    options:
      description: JSON policy document if you want to add custom actions
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add to all resources.
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: allow_cloudwatch_logs_query
    options:
      description: Allows StartQuery/StopQuery/FilterLogEvents CloudWatch actions
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: allow_predefined_sts_actions
    options:
      description: Allows GetCallerIdentity/GetSessionToken/GetAccessKeyInfo sts actions
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: allow_web_console_services
    options:
      description: Allows List/Get/Describe/View actions for services used when browsing
        AWS console (e.g. resource-groups, tag, health services)
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: web_console_services
    options:
      description: List of web console services to allow
      override:
        type: allowed
    value: '["resource-groups", "tag", "health", "ce"]'
    valueType: hcl
  version: v1
  versionState: active
