apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-iam-assumable-role-with-saml
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-iam/modules
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create_role
    options:
      description: Whether to create a role
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: provider_id
    options:
      description: ID of the SAML Provider. Use provider_ids to specify several IDs.
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: provider_ids
    options:
      description: List of SAML Provider IDs
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: aws_saml_endpoint
    options:
      description: AWS SAML Endpoint
      override:
        type: allowed
    value: '"https://signin.aws.amazon.com/saml"'
    valueType: hcl
  - name: tags
    options:
      description: A map of tags to add to IAM role resources
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: role_name
    options:
      description: IAM role name
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: role_name_prefix
    options:
      description: IAM role name prefix
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: role_description
    options:
      description: IAM Role description
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: role_path
    options:
      description: Path of IAM role
      override:
        type: allowed
    value: '"/"'
    valueType: hcl
  - name: role_permissions_boundary_arn
    options:
      description: Permissions boundary ARN to use for IAM role
      override:
        type: allowed
    value: '""'
    valueType: hcl
  - name: max_session_duration
    options:
      description: Maximum CLI/API session duration in seconds between 3600 and 43200
      override:
        type: allowed
    value: "3600.0"
    valueType: hcl
  - name: role_policy_arns
    options:
      description: List of ARNs of IAM policies to attach to IAM role
      override:
        type: allowed
    value: '[]'
    valueType: hcl
  - name: number_of_role_policy_arns
    options:
      description: Number of IAM policies to attach to IAM role
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: force_detach_policies
    options:
      description: Whether policies should be detached from this role when destroying
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: allow_self_assume_role
    options:
      description: Determines whether to allow the role to be [assume itself](https//aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/)
      override:
        type: allowed
    value: "false"
    valueType: hcl
  - name: trusted_role_actions
    options:
      description: Additional role actions
      override:
        type: allowed
    value: '["sts:AssumeRoleWithSAML", "sts:TagSession"]'
    valueType: hcl
  version: v1
  versionState: active
