apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-cloudwatch-log-metric-filter
  project: madhueaasutility
spec:
  agents:
  - name: madhuagent210
  contexts:
  - name: rafay-aws-madhueaasutility
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-cloudwatch
    name: eaas-repo-madhu-utility-madhueaasutility
  variables:
  - name: create_cloudwatch_log_metric_filter
    options:
      description: Whether to create the Cloudwatch log metric filter
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: name
    options:
      description: A name for the metric filter.
      override:
        type: allowed
    value: ''''''
    valueType: hcl
  - name: pattern
    options:
      description: A valid CloudWatch Logs filter pattern for extracting metric data
        out of ingested log events.
      override:
        type: allowed
    value: $("pattern-\(environment.name)")$
    valueType: expression
  - name: log_group_name
    options:
      description: The name of the log group to associate the metric filter with
      override:
        type: allowed
    value: ''''''
    valueType: hcl
  - name: metric_transformation_name
    options:
      description: The name of the CloudWatch metric to which the monitored log information
        should be published (e.g. ErrorCount)
      override:
        type: allowed
    value: ''''''
    valueType: hcl
  - name: metric_transformation_namespace
    options:
      description: The destination namespace of the CloudWatch metric.
      override:
        type: allowed
    value: ''''''
    valueType: hcl
  - name: metric_transformation_value
    options:
      description: What to publish to the metric. For example, if you're counting
        the occurrences of a particular term like 'Error', the value will be '1' for
        each occurrence. If you're counting the bytes transferred the published value
        will be the value in the log event.
      override:
        type: allowed
    value: '"1"'
    valueType: hcl
  - name: metric_transformation_default_value
    options:
      description: The value to emit when a filter pattern does not match a log event.
        Conflicts with `metric_transformation_dimensions`.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: metric_transformation_unit
    options:
      description: The unit to assign to the metric. If you omit this, the unit is
        set as None.
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: metric_transformation_dimensions
    options:
      description: The additional dimensions to assign to the metric, in the form
        `\
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
