apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: eks-resource-template
  project: dev-project
spec:
# Here we are defining provider as opentofu to use, if no providerOptions is mentioned then Rafay will use latest version 
  provider: opentofu
  providerOptions:
    openTofu:
      backendType: system
      refresh: true
  repositoryOptions:
# Here we are associating code in repository to the resource template
    branch: dev
    directoryPath: development-guide-templates/terraform/eks
    name: envmgr
  resources:
# Here we are defining dependency on VPCResourceTemplate, so that this resource template runs only after VPCResourceTemplate is successfully run
    - kind: resourcetemplate
      name: vpc-resource-template
      resourceOptions:
        version: v1
      type: dynamic
      dependsOn:
        - name: vpc-resource-template
  variables:
# Here we are defining input collection variable for aws_region which in turn would be passed onto the underlying IaC code
  - name: eks_cluster_project
    options:
      override:
        type: allowed
    value: eks_cluster_project
    valueType: text
  - name: eks_cluster_region
    options:
      override:
        type: allowed
    value: us-west-2
    valueType: text
  - name: eks_cluster_name
    options:
      override:
        type: allowed
    value: EKSClusterName
    valueType: text
# Here we using the output from the VPCResourceTemplate's public_subnets information and use it for the eks_public_subnets.
  - name: eks_public_subnets
    options:
      override:
        type: notallowed
    value: $(resource."vpc-resource-template".output.public_subnets.value)$
    valueType: expression
# Here we using the output from the VPCResourceTemplate's private_subnets information and use it for the eks_private_subnets.
  - name: eks_private_subnets
    options:
      override:
        type: notallowed
    value: $(resource."vpc-resource-template".output.private_subnets.value)$
    valueType: expression
  version: v1