apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: vpc-resource-template
  project: dev-project
spec:
  # Here we are defining provider as opentofu to use, if no providerOptions is mentioned then Rafay will use latest version 
  provider: opentofu
  providerOptions:
    openTofu:
      refresh: true
      backendType: system
  repositoryOptions:
    # Here we are associating code in repository to the resource template
    name: envmr
    branch: dev-guide-templates
    directoryPath: development-guide-templates/terraform/vpc
  version: v1
