apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    service: server
  {{- include "django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.type }}
  selector:
    service: server
  {{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.server.ports | toYaml | nindent 2 -}}