apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-101-vpc-ecs-madhueaasutility
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AQC69kg4nM/Pq5Ud3xgTFnFJ9MKCh1A8LvMSGx6SFbhETtF3yTCGbMcIqMRBWcTKxATQlVZ8GN5K05uv1HWTGO98PrpFxrzlZ8HltgdC1AvJvvQ5uWi7bQxFoZ+No7ru0eC+Y73GDlQkmmqn3uGFfFexabSewd8zHZgUm9tig8/+jLhpMjzaD8a491YbcLf33QRcTIaZTw/7IhsQWdyv46A1ANX61QVnXkemKhLZVgXiETsosnjhASSVRLnD7EipBG4MkJ6RpjjHMBpRAyGNpAg5wASbEoT+W5B4HScjJh6M/3qrD0afzhePCE9EFP/Qi3Q3bUdUToqlFpIj/coMfjkOpGNnCp5eRQ7iSSC3MYQjjWwBA+jXJKzdckuztw==
    AWS_SECRET_ACCESS_KEY: AQCnwNsQ92LTIkN0ZmU5n7hvOrUCY4lzkrGZvHf+vqT5J9jd06dy6CiX2jfd57ezHsAy01Xl+wwF+V6+xBXW1fnJVMn3OZWa6udEEibWvlfHWHjp3Fy8cQn960XvDRac4LwFXC3J9CVgrzdjxHj2OeeCyOEOFe/00Jmrl4s4UNQHDSC9Nf+kH4GAdFwKj0XxIqMpqpINWTfXmitZsef0AyFd2r02oVRCx/78Ks+07hZ/kJ+RCxqhRUQADDryKQB1ZWWICsscdAKPA53vQPiCcKMKO2IEiNyGGcBm7JhRbT/GOESMZ5s5haO9uJ8CBwbD972WZMpmZQ0wfL2q1WIXooksMHjg11rV+TQeU5u6Y8qKGMepc5gVs0JvpUcewg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-101-vpc-ecs-madhueaasutility
      namespace: default

