apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${SHAREDSTORAGE_CLASS}
  resources:
    requests:
      storage: 500Mi