{
 "title": "Slinky / Slurm",
 "tags": [
  "slinky",
  "slurm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "slurm_nodes_total", "legendFormat": "Total" },
    { "expr": "slurm_nodes_allocated_total", "legendFormat": "Allocated" },
    { "expr": "slurm_nodes_idle_total", "legendFormat": "Idle" },
    { "expr": "slurm_nodes_mixed_total", "legendFormat": "Mixed" }
   ]
  },
  {
   "title": "Partition CPU Allocation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_nodes_cpus_alloc_total\n/\nslurm_partition_nodes_cpus_total",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "slurm_partition_nodes_total", "legendFormat": "{{partition}}" }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "slurm_partition_jobs_total", "legendFormat": "Total ({{partition}})" },
    {
     "expr": "slurm_partition_jobs_pending_total",
     "legendFormat": "Pending ({{partition}})"
    },
    {
     "expr": "slurm_partition_jobs_running_total",
     "legendFormat": "Running ({{partition}})"
    }
   ]
  }
 ]
}