apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  name: slurm-cluster
  project: system-catalog
spec:
  config:
    container:
      image: timrafay/slurm-cluster:1.92
      imagePullCredentials: {}
      kubeOptions:
        securityContext:
          readOnlyRootFileSystem: false
    timeoutSeconds: 3600
    type: container
  inputs:
  - data:
      envs:
      - key: NODE_SELECTOR_VALUE
        value: $(current.input.node_selector_value)$
      - key: NODE_SELECTOR_KEY
        value: $(current.input.node_selector_key)$
      - key: DOMAIN
        value: $(current.input.domain)$
      - key: MEMORY
        value: $(current.input.memory)$
      - key: GPUS
        value: $(current.input.gpus)$
      - key: CPUS
        value: $(current.input.cpus)$
      - key: COMPUTE_TAG
        value: $(current.input.compute_tag)$
      - key: COMPUTE_REPOSITORY
        value: $(current.input.compute_repository)$
      - key: SHARED_STORAGE_CLASS_NAME
        value: $(current.input.shared_storage_class_name)$
      - key: SHARED_STORAGE_SIZE
        value: $(current.input.shared_storage_size)$
      - key: PUBLIC_IP
        value: $(current.input.public_ip)$
      - key: SSH_PUB_KEY
        value: $(current.input.ssh_pub_key)$
      - key: COMPUTE_REPLICAS
        value: $(current.input.compute_replicas)$
      - key: STORAGE_CLASS_NAME
        value: $(current.input.storage_class_name)$
      - key: VAR_kubeconfig
        value: $(resource.\"res-gen-kubeconfig-user\".output.kubeconfig.value)$
      - key: NAMESPACE
        value: $(environment.name)$
      - key: ACTION
        options:
          override:
            type: notallowed
        value: $(trigger.payload.action)$
    name: wfh-context
status: {}


