apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: system-sync-madhueaasutility
  project: madhueaasutility
spec:
  active: true
  stages:
  - config:
      destinationRepo:
        path:
          name: rafay-resources
        repository: eaas-repo-madhu-utility-madhueaasutility
        revision: main
      gitToSystemSync: true
      includedResources:
      - name: Environment
      - name: EnvironmentTemplate
      - name: ConfigContext
      - name: Agent
      - name: Repository
      - name: Resource
      - name: ResourceTemplate
      - name: Pipeline
      sourceRepo:
        path:
          name: rafay-resources
        repository: eaas-repo-madhu-utility-madhueaasutility
        revision: main
      systemToGitSync: true
    name: sync
    type: SystemSync
  triggers:
  - config:
      repo:
        paths:
        - name: rafay-resources
        provider: Github
        repository: eaas-repo-madhu-utility-madhueaasutility
        revision: main
    name: eaas-trigger
    type: Webhook
